spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${SHOW_SQL:false}
server:
  port: 8103
