name: Setup Docker Deploy
description: Setup build and deploy environment
inputs:
  wif-provider:
    description: GCP WIF provider
  wif-sa:
    description: GCP WIF service account
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Google Auth
      id: auth
      uses: "google-github-actions/auth@v0"
      with:
        token_format: "access_token"
        workload_identity_provider: "${{ inputs.wif-provider }}"
        service_account: "${{ inputs.wif-sa }}"

    - name: Login to Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: asia-northeast3-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
