spring:
  datasource:
    url: jdbc:${DATABASE_URI}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${SHOW_SQL:false}
eventuate:
  outbox:
    id: 8101
server:
  port: 8101
