name: Build docker image and Deploy to Artifact Registry

on: push

jobs:
  postgres:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE_BASE: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/postgres-base
      IMAGE_SAGA: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/postgres-saga
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/setup-docker-deploy
        with:
          wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
          wif-sa: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          context: "{{defaultContext}}:database"
          target: base
          tags: |
            ${{ env.IMAGE_BASE }}:${{ github.sha }}
            ${{ env.IMAGE_BASE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push saga image
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          context: "{{defaultContext}}:database"
          target: saga
          tags: |
            ${{ env.IMAGE_SAGA }}:${{ github.sha }}
            ${{ env.IMAGE_SAGA }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  accounting-service:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/ftgo-accounting-service
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/setup-docker-deploy
        with:
          wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
          wif-sa: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          target: accounting-service
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  api-gateway:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/ftgo-api-gateway
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/setup-docker-deploy
        with:
          wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
          wif-sa: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          target: api-gateway
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  consumer-service:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/ftgo-consumer-service
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/setup-docker-deploy
        with:
          wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
          wif-sa: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          target: consumer-service
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  kitchen-service:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/ftgo-kitchen-service
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/setup-docker-deploy
        with:
          wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
          wif-sa: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          target: kitchen-service
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  order-history-service:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/ftgo-order-history-service
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/setup-docker-deploy
        with:
          wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
          wif-sa: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          target: order-history-service
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  order-service:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/ftgo-order-service
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/setup-docker-deploy
        with:
          wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
          wif-sa: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          target: order-service
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  restaurant-service:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: gcp
    env:
      IMAGE: asia-northeast3-docker.pkg.dev/ftgo-jangjunha/docker-public/ftgo-restaurant-service
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/setup-docker-deploy
        with:
          wif-provider: ${{ secrets.GCP_WIF_PROVIDER }}
          wif-sa: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          target: restaurant-service
          tags: |
            ${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
